### ISSUE TITLE
Java installation improvement

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#11]
From @rpokrywka:

> Instead of `update-alternatives --config java //(interactive)`
> one can use
> `update-alternatives --set java /usr/share/jre1.8.0_31/bin/java`

@rpokrywka Can you please explain the rationale for this change and why it is better?

**Comment by jkramarz** [comment]
We have deployed ConductR cluster using Ansible. As this way of updating alternatives is non-interactive the result and required input is more predictable, so can be successfully used for deployment automation.

**Comment by huntc** [comment]
@edwardcallahan Any thoughts?

**Comment by edwardcallahan** [comment]
Automation FTW!

The webupd8ate/java ppa we are using now works well with automation as well as system updates via apt.

The use of a version number in the proposed command would introduce maintenance.

As an issue I would suggest that this is already fixed.

**Comment by huntc** [comment]
Thanks @edwardcallahan
