### ISSUE TITLE
Improve python cli install

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#12]
From @rpokrywka:

> instead of installing pip via easy_install, python3-pip package may be installed

I believe that easy_install is the correct way of doing things, but can you please provide your rationale @rpokrywka?

**Comment by jkramarz** [comment]
Sure: as long as we use system's package manager, we're provided with one and consistent way of dealing with software updates. In my opinion, the more software we can get this way, the less effort we have to spend on security fixes.

**Comment by huntc** [comment]
@2m Comments?

**Comment by 2m** [comment]
When pip was installed via apt `python3-pip` package, we were bit by the problem [described here](http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847) when updating CLI from an older version to a newer one.

**Comment by huntc** [comment]
Thanks for the reminder. I'll close this out and consider re-opening if it keeps on raising its head.
