### ISSUE TITLE
Document max content length

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#13]
Include documentation on how to change the setting for increasing the amount of bytes that may be received for ConductR i.e. `akka.http.server.parsing.max-content-length`.

**Comment by viktorklang** [comment]
If a request exceeds the limit, couldn't the error response include why and how to "fix it".

**Comment by huntc** [comment]
Yes, good idea. :-)

**Comment by huntc** [comment]
Fixed by https://github.com/typesafehub/conductr-doc/commit/244f6eaf0d69c65750d7b6c933f339f0f46113ec and also the CLIs are being enhanced to ensure that their messages are clear.
