### ISSUE TITLE
1.1.x: Update load bundle control API

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-doc#131]
The [load bundle](http://conductr.typesafe.com/docs/1.1.x/ControlAPI#Load-a-bundle) documentation of the ConductR 1.1.x Control API is outdated. The documentation still contains the bundle attributes such as nrOfCpus and memory. The conductr code uses in `V2` the following request attributes: https://github.com/typesafehub/conductr/blob/master/conductr/src/main/scala/com/typesafe/conductr/net/version2/BundlesRoute.scala#L265-L292

**Comment by markusjura** [comment]
@fsat: Ping :-)

**Comment by huntc** [comment]
There's a PR in progress: https://github.com/typesafehub/conductr-doc/pull/130
