### ISSUE TITLE
Document to create a “docker” group under Linux

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-doc#247]
**This issue needs a change in conductr-doc and Typesafe.com**

The Docker install instructions for Ubuntu contains a section “Optional configurations”: https://docs.docker.com/engine/installation/linux/ubuntulinux/#/optional-configurations

The only optional configuration for ConductR is to create the “docker” group (only for linux).

It is not obvious for the user which optional Docker configuration to follow. Therefore, we should be explicit about it in our Getting started guice, i.e. we should describe that the user need to add a “docker” group (only in a separate linux instruction).

**Comment by longmuir** [comment]
I believe this issue is taken care of by: PR #308 and #311 - can you confirm Marcus?

**Comment by markusjura** [comment]
Yes, that's correct. The issue can be closed.
