### ISSUE TITLE
Bundling-Existing.html doesn't exist

### ISSUE THREAD

**Issue by sergiuszkierat** [typesafehub/conductr-doc#27]
There is a linkrot i.e. **bundles**

> See the "legacy & third party bundles" section of the [bundles](https://github.com/typesafehub/conductr-doc/blob/master/src/main/play-doc/developer/Bundling-Existing.html) document for more information on that

on page [Dev-Quickstart.md](https://github.com/typesafehub/conductr-doc/blob/master/src/main/play-doc/developer/Dev-Quickstart.md)

**Comment by huntc** [comment]
Thanks - commit 19a57233587cbe8eefe58142f1b525b6d86a1d9e fixes this.
