### ISSUE TITLE
Documentation for DC/OS mode

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-doc#287]
The following sections need to be updated to document the instructions for the DC/OS mode:
- [x] Consolidated logging
- [x] Managing ConductR services

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation for DC/OS mode](https://trello.com/c/cm2xPlpi/405-documentation-for-dc-os-mode)

**Comment by markusjura** [comment]
Fixed by:
- https://github.com/typesafehub/conductr-doc/pull/353
- https://github.com/typesafehub/conductr-doc/pull/352
- https://github.com/typesafehub/conductr-doc/pull/302
