### ISSUE TITLE
No entry for $name_HOST_IP

### ISSUE THREAD

**Issue by tommpy** [typesafehub/conductr-doc#301]
While trying to wire up cassandra to my service following this doc: http://conductr.lightbend.com/docs/1.1.x/BundleEnvironmentVariables

I noticed that the HOST_IP doesn't appear as a stand alone variable, it's just referenced as part of name_HOST.

**Comment by huntc** [comment]
It is `BUNDLE_HOST_IP` as per the doc. :-)

**Comment by tommpy** [comment]
I was looking at the $name_HOST_IP not BUNDLE_HOST_IP.  Didn't realise they were the same thing, sorry.

**Comment by huntc** [comment]
No problem!
