### ISSUE TITLE
Document bundle restart

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#31]
Enhance documentation to cover off the following questions and answers:

> I deployed our application to our 3-node ConductR cluster and stopped the conductr service running on the first node (the one where our application was running) with the expectation that our application should start on one of the remaining nodes where the conductr service is still running. Is this expectation correct?

Yes.

> What are the prerequisites (configuration or code) for ConductR to be able to make an application failover to another available ConductR node?

If a bundle dies of its own accord then we do not attempt to restart it. We don't really know why it has stopped - it could be for a legitimate reason e.g. a short lived task. However if the ConductR service that was running on that node shuts down the one of the other nodes the cluster will re-schedule the bundles that were running for execution elsewhere.

**Comment by markusjura** [comment]
Addressed with PR #46
