### ISSUE TITLE
Configuring ConductR behind a proxy

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-doc#322]
We should document how to configure ConductR that operates behind a proxy. This will involve configuring a list of ConductR core instances as the backend, and the use of the "source" load balancing strategy.

@longmuir Since you have configured that already at a client project, are you able to document this?

**Comment by longmuir** [comment]
In our case, the entire cluster was behind the proxy - with no access to the outside world, so the only time the proxy was a consideration was during the initial installation (solved by configuring environment variables HTTP_PROXY and HTTPS_PROXY), and when Docker containers were used. Docker has its own proxy configuration: https://docs.docker.com/engine/admin/systemd/#http-proxy.

**Comment by huntc** [comment]
@longmuir I thought this was something you mentioned you would do for us at some point i.e. describe how to configure HAProxy via conductr-haproxy so that the ConductR control protocol could be accessed via basic auth.

**Comment by longmuir** [comment]
Correct @huntc .. I think I'm confusing the use of the word 'proxy' here...I was thinking behind corporate proxy. 

I started that work on the CLI's Basic Auth documentation yesterday (probably should have been created in the conductr-doc repo): https://github.com/typesafehub/conductr-cli/issues/275. Expect a PR later today.

**Comment by markusjura** [comment]
Closed by https://github.com/typesafehub/conductr-doc/pull/327/files.
