### ISSUE TITLE
Configuring conductr-haproxy in sandbox / development mode

### ISSUE THREAD

**Issue by RayRoestenburg** [typesafehub/conductr-doc#343]
If you follow along at https://conductr.lightbend.com/docs/2.1.x/DynamicProxyConfiguration#creating-and-deploying-custom-haproxy-configuration to deploy a custom HA proxy configuration on __your__ __sandbox__, it will not work. It was not immediately clear to me that I would need to do something special to deploy the bundle on sandbox.

@markusjura pointed me to https://github.com/typesafehub/conductr/tree/master/conductr-haproxy/src/bundle-configuration/conductr-haproxy-dev-mode which was very helpful. This is not referenced in any way from the documentation though.

The dev-mode scripts are different (compare https://github.com/typesafehub/conductr/tree/master/conductr-haproxy/src/bundle-configuration/conductr-haproxy-dev-mode files with what is in the docs).

It would be great if a section somewhere can be added how to deploy a custom haproxy configuration on the sandbox, I think many users will find it useful to . (The relevant parts are to add a reloadHAProxy.sh script that kills the docker container and the runtime-config.sh that sets up sandbox / docker specifics)

**Comment by markusjura** [comment]
Fixed by https://github.com/typesafehub/conductr-doc/pull/345.
