### ISSUE TITLE
google-code-prettify not downloaded

### ISSUE THREAD

**Issue by markusjura** [typesafehub/conductr-doc#355]
`google-code-prettify` cannot be downloaded because the webjars library that we are using is downloaded the files from a destination where the files are now hosted anymore. I've created the PR https://github.com/webjars/prettify/pull/1 against https://github.com/webjars that solves this problem. Once a new webjar prettify version is released we need to upgrade `conductr-doc` to download the prettify sources correctly.

**Comment by huntc** [comment]
@markusjura Is this issue now resolved?

**Comment by markusjura** [comment]
Yes, solved by https://github.com/typesafehub/project-doc/pull/53
