### ISSUE TITLE
De-prioritise the position of creating OCI bundles

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#385]
De-prioritise the position of creating the OCI Bundle at http://conductr.lightbend.com/docs/2.1.x/CreatingBundles#Producing-an-OCI-bundle-with-Docker - we are not there yet... perhaps by the time we get to the tech hub doc we will be.

**Comment by typesafe-tools** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [De-prioritise the position of creating OCI bundles in doc](https://trello.com/c/wBVOLhJD/773-de-prioritise-the-position-of-creating-oci-bundles-in-doc)
