### ISSUE TITLE
Doc Bundle Restarting

### ISSUE THREAD

**Issue by edwardcallahan** [typesafehub/conductr-doc#48]
As someone evaluating the resiliency provided by ConductR, I want to know when bundles will be restarted and when they should not be restarted so that I can better understand how to build highly resilient solutions.

**Comment by markusjura** [comment]
We have already this in our docs: http://conductr.typesafe.com/docs/1.0.x/ClusterTroubleshooting#Restarting-Bundles

Is this not sufficient enough? What kind of documentation should we add additionally?

**Comment by huntc** [comment]
Good point - close this @edwardcallahan ?

**Comment by edwardcallahan** [comment]
Agreed. Thanks @markusjura
