### ISSUE TITLE
Provide Java examples alongside Scala

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#59]

**Comment by markusjura** [comment]
If we provide the Java examples we should do it similar as the Play documentation does it by having one code snippet box with two tabs. Example: https://playframework.com/documentation/2.4.x/ThreadPools#Application-class-loader

**Comment by huntc** [comment]
Agreed!

**Comment by typesafe-tools** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2aYWyvJb&#x2F;121-tactical-activities"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Tactical Activities</a>

**Comment by huntc** [comment]
Superceded by #98
