### ISSUE TITLE
Document detached process scenarios

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#79]
There are some scenarios that could warrant a bundle component becoming detached and having some script controlling its exit via trapping SIGTERM and then gracefully shutting down the detached. For example, a video streaming process should only shutdown when it detects that its existing connections have terminated. Reddis is also another example whereupon it seemingly likes to detach itself on receipt of a SIGTERM.

We should document how to handle such use cases. The `BundleConfiguration.md` may be a good place to do so.

**Comment by edwardcallahan** [comment]
http://conductr.typesafe.com/docs/1.0.x/BundleConfiguration#When-you-cannot-Dockerize-existing-services---a-Redis-example
